[package]
name = "sbchargelimit"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
btleplug = "0.11.5"
tokio = { version = "1.38.0", features = ["full"] }
tokio-stream = "0.1.15"
uuid = "1.8.0"
